name: Build

on:
  push:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ["2.7", "3.0", "3.1", "3.2", jruby]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      BUNDLE_WITHOUT: "extras"
      CI: 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec sidekiq -r ./spec/dummy_app/app.rb &
          sleep 1
          bundle exec rspec spec